### ISSUE TITLE
Is anyone interested in a Game Design Guides section?  

### ISSUE THREAD

**Issue by HummusSamurai** [ellisonleao/magictools#121]
These would include tutorials regarding general game design, level design, and music composition for video games.

I have a decent list of such resources for my own use and would love to share it if possible.

**Comment by HaitaoBio** [comment]
In my opinion, you may add a part named Stuff Resource and put the decent list into it with appropriate description.

**Comment by ellisonleao** [comment]
@HummusSamurai sounds good, Can you put a new section called `Game design` with the game design/ level design tools? As for music composition, we already got a `Audio` section, where you can put links on. 

If you have any courses/blogs/etc about learning those , please add them into the `Lean` section.

Looking forward to check the pull request!

**Comment by ellisonleao** [comment]
@HummusSamurai any updates?

**Comment by vicenterusso** [comment]
+1 here :)

**Comment by HummusSamurai** [comment]
@ellisonleao Got a bit caught up for a while, but I'm still here and the resource ain't going anywhere.

Keep in mind it's not tools as much as guides and such, so it'll likely go under the `Learn` section under a `Game Design` sub-section.

Could be something of massive scope, really, so I'm also worried it might be too much.

**Comment by ellisonleao** [comment]
I see. If you think you can add just only the links that you think are most important, feel free to open a pull request.  I am happy to check them
