### ISSUE TITLE
Interactive fiction

### ISSUE THREAD

**Issue by Jerimee** [ellisonleao/magictools#122]
You might consider adding inform 7 and inkl to the list.

**Comment by ellisonleao** [comment]
hey @Jerimee feel free to open a Pull Request with the links. I would highly appreciate it!

**Comment by ellisonleao** [comment]
any updates @Jerimee ?

**Comment by Jerimee** [comment]
Soul is willing, flesh is weak.

here is link for ink: http://www.inklestudios.com/ink/

and here is home page for inform: http://inform7.com/

sorry for failing to open pull request...

**Comment by ellisonleao** [comment]
No problem i will add it then. Thanks for the suggestions!
