### ISSUE TITLE
Change license images with emojis

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/magictools#123]
Free - `:free:` :free:
Open Source - `:tada:` :tada:
Paid - `:moneybag:` :moneybag:
Partially Free - `:money_with_wings:` :money_with_wings:

For simplifying paid versions, if a tool has any paid version, let's use the `Partially free` type.

Example:

```
- :tada: [some link](http://www.google.com) - Description
```

- :tada: [some link](http://www.google.com) - Description

**Comment by StuffBySpencer** [comment]
I can work on this for you, just give me an hour or two :)

**Comment by theshteves** [comment]
Love this!  Let's finish applying emojis to the rest of the tools & close this up.
