### ISSUE TITLE
Missing 'opensource' and 'commercial' images

### ISSUE THREAD

**Issue by wizzup** [ellisonleao/magictools#152]
https://github.com/ellisonleao/magictools#modeling

`opensource` link to missing https://github.com/ellisonleao/magictools/blob/master/img/opensource.png

`commercial` linked to missing https://github.com/ellisonleao/magictools/blob/master/img/commercial.png

**Comment by ellisonleao** [comment]
hey @wizzup thanks for the heads up! that should be replaced with the emojis listed on #123
