### ISSUE TITLE
Recommending spritemate.com

### ISSUE THREAD

**Issue by Esshahn** [ellisonleao/magictools#156]
Hi Ellison, thank you for sharing this fantastic list, deserved one of the rare browser bookmarks. May I recommend adding http://www.spritemate.com to the list? It's a browser based online sprite editor for the Commodore 64, also on GitHub: https://github.com/Esshahn/spritemate

Cheers, and again: thanks!

**Comment by ellisonleao** [comment]
hey @Esshahn , thanks for the compliments! Can you please add a PR adding your link, please?
