### ISSUE TITLE
Orx - Portable Game Engine

### ISSUE THREAD

**Issue by heydojo** [ellisonleao/magictools#168]
Orx - Portable Game Engine
https://github.com/ellisonleao/magictools#engines-and-frameworks

[Orx](http://orx-project.org/)
[https://github.com/orx/orx](https://github.com/orx/orx)

**Comment by ellisonleao** [comment]
hey @heydojo thanks for the suggestion! Can you open a PR and add this link, please?

**Comment by heydojo** [comment]
Sorry, I don't use github anymore. This will be my last time logging in if I can help it.
Good luck!
