### ISSUE TITLE
DragonBones page is being redirected somewhere else

### ISSUE THREAD

**Issue by dejaime** [ellisonleao/magictools#169]
In DragonBones page we have the following snippet:
` <meta http-equiv="Refresh" content="0;url=http://www.effecthub.com"> `

It redirects to a seemingly unrelated page, no idea why that is there.

Is it possible to change the dragonbones link so it points to its GitHub page instead?

Thanks

**Comment by ellisonleao** [comment]
@dejaime do you have the right URL?

**Comment by dejaime** [comment]
Thank you!
