### ISSUE TITLE
Add EnTT to Engines and Frameworks

### ISSUE THREAD

**Issue by skypjack** [ellisonleao/magictools#176]
Hello,

Before to create a PR I want to ask if it's worth it according to your goal.  
EnTT started as a fast ECS in C++ a while ago and now is getting a general purpose framework for game development. [Here](https://github.com/skypjack/entt) is the link to the project.  
At a first glance, it seems to me that it's good fit for the section mentioned in the title. What about?

Thanks.

**Comment by ellisonleao** [comment]
sure @skypjack ! feel free to open a PR to add it!
