### ISSUE TITLE
Add my 2d framework

### ISSUE THREAD

**Issue by digitsensitive** [ellisonleao/magictools#178]
Hello there!

Nice list. Could you add my 2d framework written in TypeScript to your list? Would be nice! Thank you very much!

* :tada: [Juno](https://github.com/digitsensitive/juno) - Clean and lightweight 2D game framework written in TypeScript

**Comment by ellisonleao** [comment]
hey @digitsensitive , feel free to open a PR and i will be glad to add it into the list.
