### ISSUE TITLE
Plz add Wolf RPG Editor to Game Engine

### ISSUE THREAD

**Issue by fenixnix** [ellisonleao/magictools#204]
Wolf RPG Editor is free Game Engine like RPG Maker

**Comment by EllieLockhart** [comment]
If this hasn't been done yet, I'd be happy to take it on.

**Comment by ellisonleao** [comment]
sure @EllieLockhart

**Comment by EllieLockhart** [comment]
Based on reviewing Wolf RPG Editor, I'm not sure it meets the project criteria for inclusion; it's essentially an open source tool for editing RPG Maker games, without full functionality. Do we want to include it regardless?

**Comment by ellisonleao** [comment]
If its gamedev related, for sure.

**Comment by agentcobra** [comment]
@fenixnix 
Done ?
issue still opened

**Comment by ellisonleao** [comment]
Please open PR if you think this needs to be included
