### ISSUE TITLE
Corona SDK -> Solar2D

### ISSUE THREAD

**Issue by williamd1k0** [ellisonleao/magictools#218]
**Corona SDK** was recently open-sourced and is now being rebranded to **Solar2D**.

Which approach should be used to update it on the list (in addition to marking it as open-source)?
1. Rename Corona SDK to Solar2D;
2. Keep Corona SDK and add Solar2D (for backwards compatibility); `temporarily`
3. Do nothing for now (since the rebranding is not yet complete);

***
Sources:
- https://coronalabs.com/blog/2020/02/12/corona-labs-annual-update/
- https://coronalabs.com/blog/2020/04/30/future-of-corona/
- https://solar2d.com/

**Comment by ellisonleao** [comment]
Can you please open a PR to fix these?
