### ISSUE TITLE
Looseleaf is a dead link to Japanese Geocities

### ISSUE THREAD

**Issue by EllieLockhart** [ellisonleao/magictools#221]
The link to Looseleaf unfortunately appears to go to Geocities dot jp, which seems no more a thing anymore than Geocities dot com (r.i.p.). I would suggest that the link be removed so as not to get people's hopes up, and in the interest of accuracy.

**Comment by ellisonleao** [comment]
ok, can you fix it in a PR please?

**Comment by ellisonleao** [comment]
ref #224
