### ISSUE TITLE
Links information

### ISSUE THREAD

**Issue by RadRussianRus** [ellisonleao/magictools#240]
Hello! I wanted to report about outdated info on some links in Engines and Frameworks section.

- [x] Agen (http://2dengine.com/): I don't see any engine named Agen on their site. There are some tutorials in [Development section](https://2dengine.com/?p=tutorials), but other than that there isn't any engine.
- [x] AndEngine (http://www.andengine.org/): site returns "Forbidden" error.
- [x] Bacon2D (http://bacon2d.com/): turned into some Swedish site about online gambling.
- [x] Cerberus X (https://www.cerberus-x.com/wordpress/): link returns "Not found" error, but there is a forum at https://www.cerberus-x.com/community/index.php when going to https://www.cerberus-x.com/, so it's probably better to link there.
- [x] Cocos Creator (http://cocos2d-x.org/docs/editors_and_tools/creator/index.html): page leads to some docs, while it has its own page at https://www.cocos.com/en/creator.
- [x] Construct 2 (https://www.scirra.com/): it's Construct 3 now. Also consider changing emoji from 💸 to 💰, since free version is trial one.
- [x] CopperCube3D (http://www.ambiera.com/coppercube/): it's called just CopperCube on their site. Also emoji should be changed from 💰 to 💸, since there free version.
- [x] Defold (http://www.defold.com/): emoji should be changed from 🆓 to 🎉, since it's open-source (https://github.com/defold/defold).
- [x] Gorgon (https://www.tape-worm.net/): site returns "Forbidden" error.
- [x] Havok Vision (http://www.havok.com/vision-engine/): site returns "Not found" error, and there is no Vision in their projects.
- [x] Hive3D (http://www.eyelead.com/hive/): site returns "Not found" error. But there is a working link about Hive3D at https://www.eyelead.com/sites/hive/.
- [x] Loom SDK (http://loomsdk.com/): probably should be mentioned that its development has stopped, but sources still avaliable at https://github.com/LoomSDK/LoomSDK.
- [x] Lumberyard (https://aws.amazon.com/pt/lumberyard/): better to use English link instead of Portuguese (https://aws.amazon.com/lumberyard/).
- [x] MOAI (http://getmoai.com/): can't connect to server.
- [x] Monkey2 (http://monkeycoder.co.nz/): can't connect to server.
- [x] nuklear (https://github.com/vurtun/nuklear): development moved to https://github.com/Immediate-Mode-UI/Nuklear.
- [x] OpenXRay (https://github.com/OpenXRay/xray-16): emoji should be changed from 💸 to 🎉, since it's open-source and only paid option is Open Collective page for donations.
- [x] Origamijs (http://origamijs.com/docs): redirect to some Slovenian site about online gambling.
- [x] PandaJS (http://www.pandajs.net/): doesn't load properly.
- [x] Pixel Vision 8 (https://twitter.com/PixelVision8): probably it's better to link at https://pixelvision8.github.io/PixelVision8Website/, since it's their site with landing. Also emoji should be changed from 💸 to 🎉, since it's open-source (https://github.com/PixelVision8/PixelVision8) and only paid option is the paid mailing list.
- [x] QICI (http://www.qiciengine.com/): can't connect to server.
- [x] Xenko (http://xenko.com/): it's called Stride now.

- - -
Also I'm suggesting to add DungeonScript (http://dungeonscript.farbs.org/) to Engines and Frameworks section.

**Comment by ellisonleao** [comment]
hey @RadRussianRus thanks for the updates! about the missing links, i have an outaded script to check that and theres already an issue to fix that. I will fix the others.

**Comment by RadRussianRus** [comment]
Also it seems that Corona SDK (https://coronalabs.com/) is now Solar2D (https://solar2d.com/), and it's open-source (https://github.com/coronalabs/corona).
