### ISSUE TITLE
Add ÖbEngine in the free game engines

### ISSUE THREAD

**Issue by SuperFola** [ellisonleao/magictools#243]
Hi!

ÖbEngine is free modern C++ game engine on top of the SFML 2.5.1, using Lua as its scripting language, working on Windows, Linux and MacOS.

It's sponsored by a few big companies such as JetBrain, DigitalOcean and GitHub, just so you know it's not another project which will go under water in 2 weeks.

https://github.com/Sygmei/ObEngine

**Comment by ellisonleao** [comment]
Hey, @SuperFola feel free to open a PR to include this.
