### ISSUE TITLE
suggested engine/framework link: Mini Micro

### ISSUE THREAD

**Issue by JoeStrout** [ellisonleao/magictools#255]
Since you list PICO-8 and TIC-80, you should certainly include:

🎉 [Mini Micro](https://miniscript.org/MiniMicro/) - Mini Micro is a fantasy computer for making, playing and sharing 2D games and programs written in the modern [MiniScript](https://miniscript.org) language.

**Comment by ellisonleao** [comment]
hey @JoeStrout feel free to open a PR with new suggestions!

**Comment by JoeStrout** [comment]
I would, but I can't figure out how!  Forgive me, I'm still pretty new to GitHub.

I forked your repo and committed the change on my end: https://github.com/JoeStrout/magictools/commit/4dcf90dde25ce3dbe8295ac6c9bf068e8e83858a

Now according to the [docs](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork), there should be a "Pull request" button under the "Code" button on your repo.  But there isn't.  I've googled and searched, but I'm stumped.

What do I have to do to open a PR for this change?

**Comment by ellisonleao** [comment]
That's totally fine @JoeStrout !  The pull request button should be visible on your fork, right at the top right side, just like this image:

![Screenshot from 2021-07-29 12-58-15](https://user-images.githubusercontent.com/178641/127525451-2e481112-a351-4b60-8d19-1d4cec0849db.png)


I can create the Pull Request if you are having issues. Just let me know

**Comment by JoeStrout** [comment]
Thanks!  I see it now.  PR submitted.  Thanks for helping me learn how to do that!
