### ISSUE TITLE
RPG, GM, DM, board game scenario creations etc tools welcome?

### ISSUE THREAD

**Issue by ChrisChinchilla** [ellisonleao/magictools#257]
Hey there, I've wanted to write a blog post, create a list, do something with a bunch of loosely connected tools, in my mind anyway. These are tools such as Dholes House, Medieval Fantasy Generator, Foundry VTT, Roll20, Inkarnate, Owl Bear, Campaign cartographer, and many others… Also tools for creating scenarios for Chronicles of Crime, Mansions of Madness, Descent, etc etc.

Would contributions like this be welcome to your list, or do you think a new list is better? I have a quite a few to add, and likely more in the future. I'll probably also work on an blog post alongside the listings too.

Thanks!

**Comment by ellisonleao** [comment]
hey @ChrisChinchilla thanks for the issue. I think you can try right now to find the best section in our current division for each item you have, and we discuss it in each pull request, what do you think? Depending on the size of the links, multiple PRs would be easier to review

**Comment by ChrisChinchilla** [comment]
@ellisonleao Sure! I wrote the blog post of the list a while ago, but it will grow over time, and next iteration I'll make some PRs here too
