### ISSUE TITLE
Find a way of labeling the tools licenses

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/magictools#26]
There are many tools that have proprietary licenses and some of them are open source. We need to find a way of labeling those on the README file.

**Comment by arjankuijpers** [comment]
or make icons find icons for the licenses, instead of numbers.

**Comment by dkhamsing** [comment]
You can also use code markup like `free`, `gpl`, etc

**Comment by seanohue** [comment]
It would also be useful to link the emoji/icon/markup to a description of each license as well, for those too lazy to google it 💯

**Comment by ellisonleao** [comment]
@Kavex did an awesome job, so i will close this for now. We can keep using what we have now.
