### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [ellisonleao/magictools#58]
We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by ellisonleao** [comment]
Nice idea, but we already got something similar https://github.com/bayandin/awesome-awesomeness
and there is also a web service with a similar idea: https://zeef.com/

You can probably fork this repo and maintain it updated for this organization. Is that ok?
thanks!

**Comment by jeffreyjackson** [comment]
We are working on creating an open organization to further improve the awesomeness :grimacing:

By having everything under 1 organization visibility will be increased for all awesome repos -> more stars -> round we go.
Ownership is shared so there is less risk of the repo falling off unsupported.
The most popular awesome list isn't currently being updated as often as we'd like. Having it under an organization should help assist in keeping it current.
tl;dr
more stars, more people, more support

the original admin will continue to have admin rights so they'll have the same level of control as always.

**Comment by jeffreyjackson** [comment]
Ideally we would like to get @bayandin's support and move the list to the organization.
