### ISSUE TITLE
Add descriptions to all links

### ISSUE THREAD

**Issue by arthurvr** [ellisonleao/magictools#68]
Some links have a quick description of what it is:

> Agen - Cross-Platform framework for making 2D games with Lua, compatible iOS, Mac and Windows devices.

Some links don't have this. The books for example. Without a description it's kinda useless. *Why should I read this? What special about this book? Where's it about?*

Maybe consider adding descriptions to all links?

**Comment by ellisonleao** [comment]
Good  suggestion @arthurvr. Can we have a basic structure to books descriptions? Like `Editor - Where to buy - Short Description` or something like that.

**Comment by arthurvr** [comment]
I like this: https://github.com/sindresorhus/awesome-scifi

**Comment by ellisonleao** [comment]
Hm, i think this is kinda big for our list. Unless we have a different .md for the books, that will not work.

**Comment by arthurvr** [comment]
Why would the length matter?

**Comment by ellisonleao** [comment]
I believe short descriptions can increase the list readability, and since that list only works as an "index", it has to contain short texts.
