### ISSUE TITLE
Add Ads section

### ISSUE THREAD

**Issue by ellisonleao** [ellisonleao/magictools#77]

**Comment by gnuwilliam** [comment]
Nice! :+1:

**Comment by ellisonleao** [comment]
Replying via Email

2015-12-01 13:28 GMT-02:00 William Oliveira <notifications@github.com>:

> Nice! [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonleao/magictools/issues/77#issuecomment-161001427>
> .
>



-- 

Ellison Leão
about.me/ellison
[image: Ellison Leão on about.me]
  <http://about.me/ellison>
