### ISSUE TITLE
Fix Godot's Description please

### ISSUE THREAD

**Issue by Dillybob92** [ellisonleao/magictools#95]
..and also can u put it under 2d instead? New 3d Renderer is still being worked on, but 2d it's top tier atm, thanks!! <3

**Comment by williamd1k0** [comment]
What about "**An advanced, feature-packed, multi-platform 2D and 3D open-source game engine**" (the description on official site)?

Also, I agree that godot should be in the 2D category...

**Comment by Dillybob92** [comment]
@williamd1k0 Yeah for sure. That sounds awesome, lol thank you

**Comment by ellisonleao** [comment]
Fixed on #96 .
